# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='\u0424\u0418\u041e')),
                ('profession', models.CharField(max_length=255, verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u044f')),
                ('description', models.TextField(max_length=1000, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u0430',
                'verbose_name_plural': '\u0421\u043f\u0435\u0446\u0430\u043b\u0438\u0441\u0442\u044b',
            },
        ),
    ]
