# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_discountcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u044d\u0433')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('price', models.CharField(max_length=255, verbose_name='\u0426\u0435\u043d\u0430')),
                ('is_active', models.BooleanField(default=False, help_text='\u041f\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u0433\u0430\u043b\u043e\u0447\u043a\u0443, \u0447\u0442\u043e\u0431\u044b \u0432\u044b\u0432\u0435\u0441\u0442\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435', verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0443',
                'verbose_name_plural': '\u041f\u043e\u0434\u0430\u0440\u043e\u0447\u043d\u044b\u0435 \u041a\u0430\u0440\u0442\u044b',
            },
        ),
    ]
