# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='type_of_gallery',
            field=models.CharField(choices=[('interior', '\u0418\u043d\u0442\u0435\u0440\u044c\u0435\u0440'), ('world_of_beauty', '\u041c\u0438\u0440 Beauty Spa'), ('products', '\u041f\u0440\u043e\u0434\u0443\u043a\u0446\u0438\u044f'), ('life_style', '\u0421\u0442\u0438\u043b\u044c \u0436\u0438\u0437\u043d\u0438')], max_length=255, null=True),
        ),
    ]
