# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180419_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='description',
            field=models.TextField(default=1, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
