# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_license_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('consulting', '\u0414\u0438\u0430\u0433\u043d\u043e\u0441\u0442\u0438\u043a\u0430 \u0438 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f'), ('medicine', '\u041a\u043e\u0441\u043c\u0435\u0442\u043e\u043b\u043e\u0433\u0438\u044f \u0438 \u044d\u0441\u0442\u0435\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0430'), ('spa', 'Spa \u0442\u0435\u0440\u0430\u043f\u0438\u044f'), ('bath_spa', '\u0411\u0430\u043d\u043d\u044b\u0439 spa'), ('art_beauty', '\u0410\u0440\u0442 \u0438 \u0411\u044c\u044e\u0442\u0438 \u0441\u0442\u0443\u0434\u0438\u044f')], default=1, max_length=255, verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e'),
            preserve_default=False,
        ),
    ]
