# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcard',
            name='image',
            field=models.ImageField(default=1, upload_to='images/certificate_images', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountcertificate',
            name='image',
            field=models.ImageField(default=1, upload_to='images/certificate_images', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
