# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20180507_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0438\u044f \u0440\u0430\u0431\u043e\u0442\u044b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='\u0412\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u043e \u0440\u0430\u0431\u043e\u0442\u044b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discountcard',
            name='image',
            field=models.ImageField(upload_to='images/certificate_images', verbose_name='Image '),
        ),
        migrations.AlterField(
            model_name='discountcertificate',
            name='image',
            field=models.ImageField(upload_to='images/certificate_images', verbose_name='Image 320x250'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/gallery_images', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 (\u043d\u0435 \u0434\u043e\u043b\u0436\u043d\u043e \u0431\u044b\u0442\u044c >1MB)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='images/partners_images', verbose_name='\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u043e\u0431\u044a\u0435\u043a\u0442\u0430 167x52'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/slider_images', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 (659x768)'),
        ),
    ]
