# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20180516_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('consulting', '\u0414\u0438\u0430\u0433\u043d\u043e\u0441\u0442\u0438\u043a\u0430 \u0438 \u043a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u044f'), ('medicine', '\u041a\u043e\u0441\u043c\u0435\u0442\u043e\u043b\u043e\u0433\u0438\u044f \u0438 \u044d\u0441\u0442\u0435\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0430'), ('spa', 'Spa \u0442\u0435\u0440\u0430\u043f\u0438\u044f'), ('bath_spa', '\u0411\u0430\u043d\u043d\u044b\u0439 spa'), ('art_beauty', '\u0410\u0440\u0442 \u0438 \u0411\u044c\u044e\u0442\u0438 \u0441\u0442\u0443\u0434\u0438\u044f')], max_length=150, verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044e')),
                ('image', models.ImageField(upload_to='images/service_images', verbose_name='\u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 1318x380')),
            ],
            options={
                'verbose_name': '\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0443',
                'verbose_name_plural': '\u0424\u043e\u043d\u043e\u0432\u044b\u0435 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u0438 \u0440\u0430\u0437\u0434\u0435\u043b\u0430 \u0423\u0441\u043b\u0443\u0433\u0438',
            },
        ),
    ]
