# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_specialoffer_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u043e\u0431\u044a\u0435\u043a\u0442',
                'verbose_name_plural': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0435\u0442\u0438',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='facebook',
            field=models.CharField(default=1, max_length=300, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='instagram',
            field=models.CharField(default=1, max_length=300, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 instagram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='youtube',
            field=models.CharField(default=1, max_length=300, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 youtube'),
            preserve_default=False,
        ),
    ]
