# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20180516_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default=1, upload_to='images/promotion', verbose_name='Image 1318x790'),
            preserve_default=False,
        ),
    ]
