# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-27 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20180718_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPAKitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='')),
            ],
            options={
                'verbose_name_plural': 'SPA Кухня',
            },
        ),
    ]
