# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-27 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_spakitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spakitchen',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='SPA кухня: картинка'),
        ),
    ]
